### ISSUE TITLE
Provide a way to disable a FileLog

### ISSUE THREAD

**Issue by DQKrait** [vostok/logging.file#8]
Scenario:
A FileLog is configured with a config provider. Initially, log file name is not known and the config provider returns the default config. When the log file name is determined, config is updated, but some log messages may be written before that, and they end up in a file named 'log'. The desired behavior is to ignore such messages.

Possible solution is to add IsEnabled property to FileLogSettings.

Now the problem can be solved by setting EnabledLogLevels to an empty array, but it's quite ugly.

**Comment by iloktionov** [comment]
Closing as we've been unable to reconstruct the use-case this issue refers to.
